# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bhm-admin}
  s.version = "1.0.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock"]
  s.date = %q{2011-06-11}
  s.description = %q{Provides a reasonably dynamic and simple to use admin area for Rails 3 application. Built on a bunch of open source libraries.}
  s.email = %q{sutto@sutto.net}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "app/controllers/admin/base_controller.rb",
    "app/controllers/admin_controller.rb",
    "app/views/admin/shared/_edit_base.html.haml",
    "app/views/admin/shared/_footer.html.haml",
    "app/views/admin/shared/_header.html.haml",
    "app/views/admin/shared/_new_base.html.haml",
    "app/views/admin/shared/_sections.html.haml",
    "app/views/admin/shared/_sidebar.html.haml",
    "app/views/layouts/admin.html.haml",
    "bhm-admin.gemspec",
    "config/locales/en.yml",
    "lib/bhm-admin.rb",
    "lib/bhm/admin.rb",
    "lib/bhm/admin/engine.rb",
    "lib/bhm/admin/presentation_helper.rb",
    "lib/bhm/admin/sidebar_helper.rb",
    "lib/generators/bhm_admin/resource/resource_generator.rb",
    "lib/generators/bhm_admin/resource/templates/_form.html.haml",
    "lib/generators/bhm_admin/resource/templates/controller.rb",
    "lib/generators/bhm_admin/resource/templates/edit.html.haml",
    "lib/generators/bhm_admin/resource/templates/index.html.haml",
    "lib/generators/bhm_admin/resource/templates/new.html.haml",
    "lib/generators/bhm_admin/resource/templates/show.html.haml"
  ]
  s.homepage = %q{http://github.com/YouthTree/bhm-admin}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{General Admin Area stuff extracted from the big-help-mob web application.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<inherited_resources>, [">= 0"])
      s.add_runtime_dependency(%q<show_for>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<simple-navigation>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<youthtree-helpers>, [">= 0"])
      s.add_runtime_dependency(%q<nestive>, [">= 0"])
    else
      s.add_dependency(%q<inherited_resources>, [">= 0"])
      s.add_dependency(%q<show_for>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<simple-navigation>, [">= 0"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<youthtree-helpers>, [">= 0"])
      s.add_dependency(%q<nestive>, [">= 0"])
    end
  else
    s.add_dependency(%q<inherited_resources>, [">= 0"])
    s.add_dependency(%q<show_for>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<simple-navigation>, [">= 0"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<youthtree-helpers>, [">= 0"])
    s.add_dependency(%q<nestive>, [">= 0"])
  end
end

